# Generated by Django 5.0.6 on 2024-06-28 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('dr', 'Dr.'), ('prof_dr.', 'Prof. Dr.'), ('Dr_rer_nat', 'Dr. rer. nat')], max_length=20)),
                ('speciality', models.CharField(choices=[('allgemeinedizin', 'Allgemeinedizin'), ('radiologe', 'Radiologe'), ('hautarzt', 'Hautarzt')], max_length=50)),
            ],
        ),
    ]
