# Generated by Django 5.0.6 on 2024-06-28 17:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_tool', '0005_appointment_appointment_date_appointment_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='created_at',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
