# Generated by Django 5.0.6 on 2024-06-29 07:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_tool', '0006_alter_appointment_created_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='title',
            field=models.CharField(choices=[('dr', 'Dr.'), ('prof_dr.', 'Prof. Dr.'), ('dr_rer_nat', 'Dr. rer. nat')], max_length=20),
        ),
    ]
